[DEVICE1]
; Настройки для первого устройства
name = ЮНИТ-М500-ОЛ
version = 0.1
path_to_latex_desc = //uni-eng.ru/unit/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ500/201. РЭ ЮНИТ-М500-ОЛ
order_code = ЮНИТ-М319-ДЗТ2-Р02с-х-К002-К002-К002-К002-К002-В021-В021-В021-В021-М090.9000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ ЛИНИИ 110-220 КВ
manual_code = ЮТКБ.656122.ХХХ РЭХХ
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.ХХХ БУХХХ
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "18.09.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc =

[DEVICE2]
; Настройки для первого устройства
name = ЮНИТ-М500-БСК
version = 0.1
path_to_latex_desc = //uni-eng.ru/unit/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ500/202. РЭ ЮНИТ-М500-БСК
order_code = ЮНИТ-М319-ДЗТ2-Р02с-х-К002-К002-К002-К002-К002-В021-В021-В021-В021-М090.9000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ БСК 110-220 КВ
manual_code = None
order_code_hmi = None
setting_blanc_code = None
versions = [{"edition": "0.1", "data": "18.03.2026"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = None